version: "3.8"
services:
  backend:
    build:
      context: ./server
    environment:
      - MONGODB=mongodb://lightweight-asset-manager_db_1:27017
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - /mongodb/lwam:/data/db
    ports:
      - 27017:27017
  nginx:
    build:
      context: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
