version: "3.8"
services:
  backend:
    build:
      context: ./server
    environment:
      - DB_USER=SA
      - DB_PASSWORD=MyPass!word
      - DB_HOST=lightweight-asset-manager_db_1
      - DB_PORT=1433
      - GQL_PORT=8080
      - TOKEN=OKTA TOKEN HERE
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass!word
      - MSSQL_PID=Express
    volumes:
      - ./db/mssql/data:/var/opt/mssql/data
      - ./db/mssql/log:/var/opt/mssql/log 
      - ./db/mssql/secrets:/var/opt/mssql/secrets

    ports:
      - 1433:1433
  nginx:
    build:
      context: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
